import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Services from "../components/Services";
import Menu from "../components/Menu";
import css from "../styles/Home.module.css"

export default function Home() {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>DELISH</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
          <Menu />
        </main>
      </div>
    </Layout>
  );
}

